# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deduplicator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x65\x64uplicator.proto\x12\x08protocol\"1\n\x11GetSimHashRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\"$\n\x12GetSimHashResponse\x12\x0e\n\x06\x62inary\x18\x01 \x01(\t2Y\n\x0c\x44\x65\x64uplicator\x12I\n\nGetSimHash\x12\x1b.protocol.GetSimHashRequest\x1a\x1c.protocol.GetSimHashResponse\"\x00\x42<Z:github.com/rnr-capital/newsfeed-backend/publisher/protocolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deduplicator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:github.com/rnr-capital/newsfeed-backend/publisher/protocol'
  _GETSIMHASHREQUEST._serialized_start=32
  _GETSIMHASHREQUEST._serialized_end=81
  _GETSIMHASHRESPONSE._serialized_start=83
  _GETSIMHASHRESPONSE._serialized_end=119
  _DEDUPLICATOR._serialized_start=121
  _DEDUPLICATOR._serialized_end=210
# @@protoc_insertion_point(module_scope)
