package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"time"

	"github.com/rnr-capital/newsfeed-backend/model"
	"github.com/rnr-capital/newsfeed-backend/server/graph/generated"
)

// DeletedAt is the resolver for the deletedAt field.
func (r *sourceResolver) DeletedAt(ctx context.Context, obj *model.Source) (*time.Time, error) {
	return &obj.DeletedAt.Time, nil
}

// Source returns generated.SourceResolver implementation.
func (r *Resolver) Source() generated.SourceResolver { return &sourceResolver{r} }

type sourceResolver struct{ *Resolver }
