// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type ColumnSeedStateInterface interface {
	IsColumnSeedStateInterface()
	GetID() string
	GetName() string
}

type FeedSeedStateInterface interface {
	IsFeedSeedStateInterface()
	GetID() string
	GetName() string
}

type UserSeedStateInterface interface {
	IsUserSeedStateInterface()
	GetID() string
	GetName() string
	GetAvatarURL() string
}

type AddSubSourceInput struct {
	SourceID          string `json:"sourceId"`
	SubSourceUserName string `json:"subSourceUserName"`
}

type AddWeiboSubSourceInput struct {
	Name string `json:"name"`
}

type ColumnRefreshInput struct {
	ColumnID          string               `json:"columnId"`
	Limit             int                  `json:"limit"`
	Direction         FeedRefreshDirection `json:"direction"`
	Cursor            int                  `json:"cursor"`
	OtherEndCursor    *int                 `json:"otherEndCursor,omitempty"`
	FeedIds           []string             `json:"feedIds"`
	FeedUpdatedTimes  []*time.Time         `json:"feedUpdatedTimes,omitempty"`
	ColumnUpdatedTime *time.Time           `json:"columnUpdatedTime,omitempty"`
	Query             *string              `json:"query,omitempty"`
	Filter            *RefreshFilterInput  `json:"filter,omitempty"`
}

type ColumnSeedState struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (ColumnSeedState) IsColumnSeedStateInterface() {}
func (this ColumnSeedState) GetID() string          { return this.ID }
func (this ColumnSeedState) GetName() string        { return this.Name }

type ColumnSeedStateInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ColumnsGetPostsInput struct {
	UserID               string                `json:"userId"`
	ColumnsRefreshInputs []*ColumnRefreshInput `json:"columnsRefreshInputs"`
}

type CustomizedCrawlerPanopticConfigForm struct {
	Name                      *string                  `json:"name,omitempty"`
	StartImmediately          *bool                    `json:"startImmediately,omitempty"`
	ScheduleEveryMilliseconds *int                     `json:"scheduleEveryMilliseconds,omitempty"`
	CustomizedCrawlerParams   *CustomizedCrawlerParams `json:"customizedCrawlerParams"`
}

type CustomizedCrawlerParams struct {
	CrawlURL                   string  `json:"crawlUrl"`
	BaseSelector               string  `json:"baseSelector"`
	TitleRelativeSelector      *string `json:"titleRelativeSelector,omitempty"`
	ContentRelativeSelector    *string `json:"contentRelativeSelector,omitempty"`
	ExternalIDRelativeSelector *string `json:"externalIdRelativeSelector,omitempty"`
	TimeRelativeSelector       *string `json:"timeRelativeSelector,omitempty"`
	ImageRelativeSelector      *string `json:"imageRelativeSelector,omitempty"`
	SubsourceRelativeSelector  *string `json:"subsourceRelativeSelector,omitempty"`
	OriginURLRelativeSelector  *string `json:"originUrlRelativeSelector,omitempty"`
	OriginURLIsRelativePath    *bool   `json:"originUrlIsRelativePath,omitempty"`
}

type CustomizedCrawlerTestResponse struct {
	BaseHTML   *string  `json:"baseHtml,omitempty"`
	Title      *string  `json:"title,omitempty"`
	Content    *string  `json:"content,omitempty"`
	ExternalID *string  `json:"externalId,omitempty"`
	Time       *string  `json:"time,omitempty"`
	Images     []string `json:"images,omitempty"`
	Subsource  *string  `json:"subsource,omitempty"`
	OriginURL  *string  `json:"originUrl,omitempty"`
}

type DeleteColumnInput struct {
	UserID   string `json:"userId"`
	ColumnID string `json:"columnId"`
}

type DeleteSubSourceInput struct {
	SubsourceID string `json:"subsourceId"`
}

type FeedRefreshInput struct {
	FeedID          string               `json:"feedId"`
	Limit           int                  `json:"limit"`
	Cursor          int                  `json:"cursor"`
	Direction       FeedRefreshDirection `json:"direction"`
	FeedUpdatedTime *time.Time           `json:"feedUpdatedTime,omitempty"`
	Query           *string              `json:"query,omitempty"`
	Filter          *RefreshFilterInput  `json:"filter,omitempty"`
}

type FeedSeedState struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (FeedSeedState) IsFeedSeedStateInterface() {}
func (this FeedSeedState) GetID() string        { return this.ID }
func (this FeedSeedState) GetName() string      { return this.Name }

type FeedSeedStateInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type FeedsGetPostsInput struct {
	UserID            string              `json:"userId"`
	FeedRefreshInputs []*FeedRefreshInput `json:"feedRefreshInputs"`
}

type NewPostInput struct {
	Title            string   `json:"title"`
	Content          string   `json:"content"`
	SubSourceID      string   `json:"subSourceId"`
	FeedsIDPublishTo []string `json:"feedsIdPublishTo,omitempty"`
	SharedFromPostID *string  `json:"sharedFromPostId,omitempty"`
}

type NewSourceInput struct {
	UserID                              string                               `json:"userId"`
	Name                                string                               `json:"name"`
	Domain                              string                               `json:"domain"`
	CustomizedCrawlerPanopticConfigForm *CustomizedCrawlerPanopticConfigForm `json:"customizedCrawlerPanopticConfigForm,omitempty"`
}

type NewUserInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NotificationSettingInput struct {
	UserID                string `json:"userId"`
	ColumnID              string `json:"columnId"`
	Mobile                bool   `json:"mobile"`
	Web                   bool   `json:"web"`
	UnreadIndicatorOnIcon bool   `json:"unreadIndicatorOnIcon"`
}

type PostInColumnOutput struct {
	Post   *Post `json:"post"`
	Cursor int   `json:"cursor"`
}

type PostInFeedOutput struct {
	Post   *Post `json:"post"`
	Cursor int   `json:"cursor"`
}

type PostInput struct {
	ID string `json:"id"`
}

type RefreshFilterInput struct {
	Unread *bool `json:"unread,omitempty"`
}

type SearchPostsInput struct {
	UserID                  string                   `json:"userId"`
	SearchPostsRefreshInput *SearchPostsRefreshInput `json:"searchPostsRefreshInput"`
}

type SearchPostsRefreshInput struct {
	Limit          int                  `json:"limit"`
	Direction      FeedRefreshDirection `json:"direction"`
	Cursor         int                  `json:"cursor"`
	OtherEndCursor *int                 `json:"otherEndCursor,omitempty"`
	Query          *string              `json:"query,omitempty"`
	Filter         *RefreshFilterInput  `json:"filter,omitempty"`
}

type SeedStateInput struct {
	UserSeedState   *UserSeedStateInput     `json:"userSeedState"`
	ColumnSeedState []*ColumnSeedStateInput `json:"columnSeedState"`
}

type SetFeedFavoriteInput struct {
	UserID     string `json:"userId"`
	FeedID     string `json:"feedId"`
	IsFavorite bool   `json:"isFavorite"`
}

type SetItemsReadStatusInput struct {
	UserID      string   `json:"userId"`
	ItemNodeIds []string `json:"itemNodeIds"`
	Read        bool     `json:"read"`
	Type        ItemType `json:"type"`
}

type SourcesInput struct {
	SubSourceFromSharedPost bool `json:"subSourceFromSharedPost"`
}

type SubscribeInput struct {
	UserID   string `json:"userId"`
	ColumnID string `json:"columnId"`
}

type SubsourcesInput struct {
	IsFromSharedPost bool  `json:"isFromSharedPost"`
	IsCustomized     *bool `json:"isCustomized,omitempty"`
}

type UpsertColumnInput struct {
	ColumnID   *string    `json:"columnId,omitempty"`
	UserID     string     `json:"userId"`
	Name       string     `json:"name"`
	Visibility Visibility `json:"visibility"`
	FeedIds    []string   `json:"feedIds,omitempty"`
}

type UpsertFeedInput struct {
	ColumnID             *string  `json:"columnId,omitempty"`
	UserID               string   `json:"userId"`
	FeedID               *string  `json:"feedId,omitempty"`
	Name                 string   `json:"name"`
	FilterDataExpression string   `json:"filterDataExpression"`
	SubSourceIds         []string `json:"subSourceIds"`
	AddToColumn          bool     `json:"addToColumn"`
}

type UpsertSubSourceInput struct {
	Name                    string                   `json:"name"`
	ExternalIdentifier      string                   `json:"externalIdentifier"`
	SourceID                string                   `json:"sourceId"`
	AvatarURL               string                   `json:"avatarUrl"`
	OriginURL               string                   `json:"originUrl"`
	IsFromSharedPost        bool                     `json:"isFromSharedPost"`
	CustomizedCrawlerParams *CustomizedCrawlerParams `json:"customizedCrawlerParams,omitempty"`
}

type UserIDInput struct {
	UserID string `json:"userId"`
}

type UserSeedState struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	AvatarURL string `json:"avatarUrl"`
}

func (UserSeedState) IsUserSeedStateInterface() {}
func (this UserSeedState) GetID() string        { return this.ID }
func (this UserSeedState) GetName() string      { return this.Name }
func (this UserSeedState) GetAvatarURL() string { return this.AvatarURL }

type UserSeedStateInput struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	AvatarURL string `json:"avatarUrl"`
}

type FeedRefreshDirection string

const (
	FeedRefreshDirectionNew FeedRefreshDirection = "NEW"
	FeedRefreshDirectionOld FeedRefreshDirection = "OLD"
)

var AllFeedRefreshDirection = []FeedRefreshDirection{
	FeedRefreshDirectionNew,
	FeedRefreshDirectionOld,
}

func (e FeedRefreshDirection) IsValid() bool {
	switch e {
	case FeedRefreshDirectionNew, FeedRefreshDirectionOld:
		return true
	}
	return false
}

func (e FeedRefreshDirection) String() string {
	return string(e)
}

func (e *FeedRefreshDirection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FeedRefreshDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FeedRefreshDirection", str)
	}
	return nil
}

func (e FeedRefreshDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ItemType string

const (
	ItemTypePost        ItemType = "POST"
	ItemTypeDuplication ItemType = "DUPLICATION"
)

var AllItemType = []ItemType{
	ItemTypePost,
	ItemTypeDuplication,
}

func (e ItemType) IsValid() bool {
	switch e {
	case ItemTypePost, ItemTypeDuplication:
		return true
	}
	return false
}

func (e ItemType) String() string {
	return string(e)
}

func (e *ItemType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemType", str)
	}
	return nil
}

func (e ItemType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SignalType string

const (
	SignalTypeSeedState          SignalType = "SEED_STATE"
	SignalTypeSetItemsReadStatus SignalType = "SET_ITEMS_READ_STATUS"
)

var AllSignalType = []SignalType{
	SignalTypeSeedState,
	SignalTypeSetItemsReadStatus,
}

func (e SignalType) IsValid() bool {
	switch e {
	case SignalTypeSeedState, SignalTypeSetItemsReadStatus:
		return true
	}
	return false
}

func (e SignalType) String() string {
	return string(e)
}

func (e *SignalType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SignalType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SignalType", str)
	}
	return nil
}

func (e SignalType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Visibility string

const (
	VisibilityGlobal  Visibility = "GLOBAL"
	VisibilityPrivate Visibility = "PRIVATE"
)

var AllVisibility = []Visibility{
	VisibilityGlobal,
	VisibilityPrivate,
}

func (e Visibility) IsValid() bool {
	switch e {
	case VisibilityGlobal, VisibilityPrivate:
		return true
	}
	return false
}

func (e Visibility) String() string {
	return string(e)
}

func (e *Visibility) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Visibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Visibility", str)
	}
	return nil
}

func (e Visibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
