# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler_publisher_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63rawler_publisher_message.proto\x12\x08protocol\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n\x10\x43rawledSubSource\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x65xternal_id\x18\x03 \x01(\t\x12\x11\n\tsource_id\x18\x04 \x01(\t\x12\x12\n\navatar_url\x18\x05 \x01(\t\x12\x12\n\norigin_url\x18\x06 \x01(\t\"\xae\x04\n\x0e\x43rawlerMessage\x12\x32\n\x04post\x18\x01 \x01(\x0b\x32$.protocol.CrawlerMessage.CrawledPost\x12.\n\ncrawled_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncrawler_ip\x18\x03 \x01(\t\x12\x17\n\x0f\x63rawler_version\x18\x04 \x01(\t\x12\x0f\n\x07is_test\x18\x05 \x01(\x08\x1a\xf9\x02\n\x0b\x43rawledPost\x12\x16\n\x0e\x64\x65\x64uplicate_id\x18\x01 \x01(\t\x12.\n\nsub_source\x18\x02 \x01(\x0b\x32\x1a.protocol.CrawledSubSource\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x12\n\nimage_urls\x18\x05 \x03(\t\x12\x12\n\nfiles_urls\x18\x06 \x03(\t\x12\x38\n\x14\x63ontent_generated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\norigin_url\x18\x08 \x01(\t\x12\x46\n\x18shared_from_crawled_post\x18\t \x01(\x0b\x32$.protocol.CrawlerMessage.CrawledPost\x12\x0c\n\x04tags\x18\n \x03(\t\x12\x36\n\x08reply_to\x18\x0b \x01(\x0b\x32$.protocol.CrawlerMessage.CrawledPostB<Z:github.com/rnr-capital/newsfeed-backend/publisher/protocolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawler_publisher_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:github.com/rnr-capital/newsfeed-backend/publisher/protocol'
  _CRAWLEDSUBSOURCE._serialized_start=78
  _CRAWLEDSUBSOURCE._serialized_end=202
  _CRAWLERMESSAGE._serialized_start=205
  _CRAWLERMESSAGE._serialized_end=763
  _CRAWLERMESSAGE_CRAWLEDPOST._serialized_start=386
  _CRAWLERMESSAGE_CRAWLEDPOST._serialized_end=763
# @@protoc_insertion_point(module_scope)
