LAMBDA_POOL_SIZE: 10
LAMBDA_LIFE_SPAN_SECOND: 300
MAINTAIN_EVERY_SECOND: 30
FORCE_REMOTE_SCHEDULE_PULL: false
SCHEDULER_CONFIG_POLL_INTERVAL_SECOND: 60 
LOCAL_PANOPTIC_CONFIG_PATH: "panoptic/data/testing_panoptic_config.textproto"
